import React, { useState } from 'react';
import { X, Copy, Check, Sparkles, Scale } from 'lucide-react';
import { ScoredClause } from '../types';

interface CounterDraftModalProps {
  clause: ScoredClause | null;
  onClose: () => void;
}

export const CounterDraftModal: React.FC<CounterDraftModalProps> = ({ clause, onClose }) => {
  const [copied, setCopied] = useState(false);

  if (!clause || !clause.counterDraft) return null;

  const handleCopy = () => {
    if (clause.counterDraft?.counterDraft) {
      navigator.clipboard.writeText(clause.counterDraft.counterDraft);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  return (
    <div
      role="dialog"
      aria-modal="true"
      aria-labelledby="counter-modal-title"
      className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200"
    >
      <div className="bg-white w-full max-w-2xl rounded-2xl shadow-2xl border border-slate-200 overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="bg-gradient-to-r from-teal-800 to-teal-700 text-white p-5 flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <div className="p-2 bg-white/10 rounded-lg">
              <Scale className="w-5 h-5 text-teal-200" />
            </div>
            <div>
              <h3 id="counter-modal-title" className="font-bold text-lg leading-tight">
                Fair Counter-Proposal: {clause.clauseType}
              </h3>
              <p className="text-xs text-teal-100 mt-0.5">
                Negotiation-ready substitute language generated by Gemini 2.5 Flash
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="text-white/80 hover:text-white p-1 rounded-lg hover:bg-white/10 transition-colors"
            aria-label="Close modal"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto space-y-5 text-sm">
          {/* Current vs Proposed Side-by-Side Comparison */}
          <div>
            <span className="text-xs uppercase font-bold text-rose-700 tracking-wider">
              Current Contract Language (Flagged: {clause.riskLevel})
            </span>
            <div className="mt-1.5 p-3.5 bg-rose-50/70 border border-rose-200 rounded-xl text-xs text-slate-700 font-mono leading-relaxed max-h-32 overflow-y-auto">
              {clause.clauseText}
            </div>
          </div>

          <div>
            <div className="flex items-center justify-between">
              <span className="text-xs uppercase font-bold text-teal-800 tracking-wider flex items-center gap-1.5">
                <Sparkles className="w-3.5 h-3.5 text-teal-600" />
                Proposed Balanced Counter-Draft
              </span>
              <button
                onClick={handleCopy}
                className="text-xs font-semibold px-2.5 py-1 bg-teal-50 text-teal-700 hover:bg-teal-100 rounded-md border border-teal-200 flex items-center gap-1 transition-colors"
                aria-label="Copy proposed counter-draft to clipboard"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                {copied ? 'Copied!' : 'Copy Clause'}
              </button>
            </div>
            <div className="mt-1.5 p-3.5 bg-teal-50/50 border border-teal-200 rounded-xl text-xs text-slate-900 font-mono leading-relaxed">
              {clause.counterDraft.counterDraft}
            </div>
          </div>

          {/* Rationale & Key Changes */}
          <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
            <h4 className="font-bold text-xs uppercase text-slate-500 tracking-wider mb-1.5">
              Why this is fair & commercially reasonable
            </h4>
            <p className="text-xs text-slate-700 leading-relaxed">
              {clause.counterDraft.explanation}
            </p>

            {clause.counterDraft.keyChanges && clause.counterDraft.keyChanges.length > 0 && (
              <ul className="mt-3 space-y-1 text-xs text-slate-600 list-disc list-inside">
                {clause.counterDraft.keyChanges.map((change, i) => (
                  <li key={i} className="leading-snug">{change}</li>
                ))}
              </ul>
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between gap-4">
          <p className="text-[11px] text-slate-400 italic">
            Informational counter-proposal. Consult with an attorney before binding agreements.
          </p>
          <div className="flex gap-2 shrink-0">
            <button
              onClick={onClose}
              className="px-4 py-2 border border-slate-300 hover:bg-slate-100 text-slate-700 text-xs font-semibold rounded-lg transition-colors"
            >
              Close
            </button>
            <button
              onClick={handleCopy}
              className="px-4 py-2 bg-teal-700 hover:bg-teal-800 text-white text-xs font-bold rounded-lg shadow-xs flex items-center gap-1.5 transition-colors"
            >
              {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              {copied ? 'Copied to Clipboard' : 'Copy Counter-Draft'}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
