import React, { useState } from 'react';
import { FileBadge, Download, Printer, Calendar, HelpCircle, ShieldAlert, Sparkles, Loader2 } from 'lucide-react';
import { LawyerDossier, PersonaType } from '../types';

interface DossierTabProps {
  documentText: string;
  documentTitle: string;
  persona: PersonaType;
}

export const DossierTab: React.FC<DossierTabProps> = ({
  documentText,
  documentTitle,
  persona,
}) => {
  const [loading, setLoading] = useState(false);
  const [dossier, setDossier] = useState<LawyerDossier | null>(null);

  const handleGenerateDossier = async () => {
    if (!documentText || documentText.trim().length < 20) {
      alert('Please upload or audit a contract document first in the "Audit & Gotchas" tab.');
      return;
    }

    setLoading(true);
    try {
      const res = await fetch('/api/documents/dossier', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          documentText,
          documentTitle: documentTitle || 'Legal Contract Review',
          persona,
        }),
      });

      if (!res.ok) {
        const textResp = await res.text();
        let errMsg = `Server returned status ${res.status}`;
        try {
          const parsed = JSON.parse(textResp);
          if (parsed.error?.message) errMsg = parsed.error.message;
        } catch {
          if (textResp && textResp.length > 0) errMsg = textResp.slice(0, 200);
        }
        alert(`Dossier generation error: ${errMsg}`);
        return;
      }

      const json = await res.json();
      if (json.success) {
        setDossier(json.data);
      } else {
        alert(`Failed to generate dossier: ${json.error?.message}`);
      }
    } catch (err) {
      alert(`Network error: ${(err as Error).message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleExportMarkdown = () => {
    if (!dossier) return;

    const md = `# Attorney Consultation Brief: ${dossier.documentTitle}
*Target Persona:* ${dossier.persona}
*Generated by LexTrace AI:* ${new Date(dossier.generatedAt).toLocaleDateString()}

---

## 1. Executive Summary
${dossier.executiveSummary}

---

## 2. High-Risk Exposure Areas
${dossier.highRiskItems.map((item) => `- **[${item.riskLevel}] ${item.clauseType}:** ${item.coreConcern}`).join('\n')}

---

## 3. Unresolved Ambiguities
${dossier.unresolvedAmbiguities.map((a) => `- ${a}`).join('\n')}

---

## 4. Top 5 Precision Questions for Legal Counsel
*(Designed to save $300+/hr in billable attorney consultations)*
${dossier.targetedAttorneyQuestions.map((q, i) => `${i + 1}. **${q.question}**\n   - *Rationale:* ${q.rationale}\n   - *Related Area:* ${q.relatedClauseType}`).join('\n\n')}

---

## 5. Signer Obligation & Deadline Calendar
| Milestone | Clause | Timeframe | Responsible Party | Action Required |
| :--- | :--- | :--- | :--- | :--- |
${dossier.obligationCalendar.map((o) => `| ${o.milestone} | ${o.clauseType} | ${o.timeframe} | ${o.responsibleParty} | ${o.actionRequired} |`).join('\n')}

---
*Notice: This dossier is prepared for informational intake purposes only. Consult with a licensed attorney.*
`;

    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `LexTrace_Attorney_Brief_${dossier.persona}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-6">
      {/* Action Header */}
      <div className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <div className="p-2 bg-teal-100 text-teal-800 rounded-xl">
              <FileBadge className="w-5 h-5" />
            </div>
            <h2 className="text-lg font-bold text-slate-900">Attorney Consultation Dossier & Calendar</h2>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Generate an exportable briefing sheet with high-value questions for legal counsel to save hundreds in billable hours.
          </p>
        </div>

        <div className="flex items-center gap-2">
          {dossier && (
            <>
              <button
                onClick={handlePrint}
                aria-label="Print or save attorney briefing sheet as PDF"
                className="px-3 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-colors focus-visible:ring-2 focus-visible:ring-teal-600 focus-visible:outline-none"
                title="Print or Save as PDF"
              >
                <Printer className="w-3.5 h-3.5" aria-hidden="true" />
                <span>Print / PDF</span>
              </button>
              <button
                onClick={handleExportMarkdown}
                aria-label="Download attorney briefing sheet as Markdown file"
                className="px-3 py-2 bg-slate-100 hover:bg-slate-200 text-slate-700 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-colors focus-visible:ring-2 focus-visible:ring-teal-600 focus-visible:outline-none"
                title="Download as Markdown"
              >
                <Download className="w-3.5 h-3.5" aria-hidden="true" />
                <span>Export .md</span>
              </button>
            </>
          )}

          <button
            onClick={handleGenerateDossier}
            disabled={loading}
            aria-label={dossier ? 'Regenerate attorney intake brief' : 'Generate attorney intake brief'}
            className="px-4 py-2.5 bg-teal-700 hover:bg-teal-800 text-white rounded-xl text-xs font-bold flex items-center gap-1.5 shadow-sm transition-colors disabled:opacity-50 focus-visible:ring-2 focus-visible:ring-teal-600 focus-visible:outline-none"
          >
            {loading ? (
              <span role="status" aria-live="polite" className="inline-flex items-center gap-1.5">
                <Loader2 className="w-4 h-4 animate-spin" aria-hidden="true" />
                <span>Generating Dossier...</span>
                <span className="sr-only">Compiling attorney intake dossier...</span>
              </span>
            ) : (
              <>
                <Sparkles className="w-4 h-4 text-teal-200" aria-hidden="true" />
                <span>{dossier ? 'Regenerate Brief' : 'Generate Intake Brief'}</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Dossier Document Display */}
      {dossier ? (
        <article className="bg-white rounded-2xl p-8 border border-slate-200 shadow-md space-y-8 print:border-none print:shadow-none print:p-0">
          {/* Header Banner */}
          <div className="pb-6 border-b border-slate-200">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-teal-700 bg-teal-50 px-2.5 py-1 rounded-md border border-teal-200">
                Confidential Attorney Intake Dossier
              </span>
              <span className="text-xs text-slate-400 font-mono">
                {new Date(dossier.generatedAt).toLocaleDateString()}
              </span>
            </div>
            <h3 className="text-2xl font-extrabold text-slate-900 mt-2">
              {dossier.documentTitle}
            </h3>
            <p className="text-xs text-slate-500 mt-0.5">
              Client Perspective: <strong>{dossier.persona}</strong> • Prepared via LexTrace AI Document Auditor
            </p>
          </div>

          {/* 1. Executive Summary */}
          <div>
            <h4 className="text-xs uppercase font-bold text-slate-500 tracking-wider mb-2">
              1. Executive Position Summary
            </h4>
            <div className="p-4 bg-slate-50 rounded-xl border border-slate-200 text-xs text-slate-800 leading-relaxed">
              {dossier.executiveSummary}
            </div>
          </div>

          {/* 2. High Risk Exposure Items */}
          <div>
            <h4 className="text-xs uppercase font-bold text-slate-500 tracking-wider mb-2 flex items-center gap-1.5">
              <ShieldAlert className="w-4 h-4 text-rose-600" />
              2. Critical Areas of Asymmetric Legal Exposure
            </h4>
            <div className="space-y-2">
              {dossier.highRiskItems.map((item, idx) => (
                <div key={idx} className="p-3 bg-rose-50/50 rounded-xl border border-rose-200/80 text-xs flex items-start justify-between gap-3">
                  <div>
                    <strong className="text-slate-900">{item.clauseType}:</strong>
                    <span className="text-slate-700 ml-1.5">{item.coreConcern}</span>
                  </div>
                  <span className="text-[10px] uppercase font-bold px-2 py-0.5 rounded-full bg-rose-100 text-rose-800 shrink-0">
                    {item.riskLevel}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* 3. Unresolved Ambiguities */}
          <div>
            <h4 className="text-xs uppercase font-bold text-slate-500 tracking-wider mb-2">
              3. Unresolved Ambiguities Requiring Clarification
            </h4>
            <ul className="space-y-1.5 text-xs text-slate-700 list-disc list-inside bg-slate-50 p-4 rounded-xl border border-slate-200">
              {dossier.unresolvedAmbiguities.map((amb, idx) => (
                <li key={idx} className="leading-relaxed">{amb}</li>
              ))}
            </ul>
          </div>

          {/* 4. Top 5 Precision Questions for Legal Counsel */}
          <div>
            <h4 className="text-xs uppercase font-bold text-teal-800 tracking-wider mb-2 flex items-center gap-1.5">
              <HelpCircle className="w-4 h-4 text-teal-700" />
              4. Top 5 High-Value Questions to Ask Your Attorney
            </h4>
            <p className="text-xs text-slate-500 mb-3">
              Ask these specific questions during your consultation to save billable hours:
            </p>
            <div className="space-y-3">
              {dossier.targetedAttorneyQuestions.map((q, idx) => (
                <div key={idx} className="p-4 bg-teal-50/40 rounded-xl border border-teal-200 text-xs space-y-1">
                  <div className="font-bold text-slate-900 text-sm flex items-start gap-2">
                    <span className="text-teal-700 font-extrabold">{idx + 1}.</span>
                    <span>{q.question}</span>
                  </div>
                  <p className="text-slate-600 pl-4 text-[11px] leading-relaxed">
                    <strong>Why ask this:</strong> {q.rationale}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* 5. Obligation Timeline */}
          <div>
            <h4 className="text-xs uppercase font-bold text-slate-500 tracking-wider mb-2 flex items-center gap-1.5">
              <Calendar className="w-4 h-4 text-slate-700" />
              5. Signer Obligation & Deadline Calendar
            </h4>
            <div className="overflow-x-auto rounded-xl border border-slate-200">
              <table className="min-w-full divide-y divide-slate-200 text-xs text-left">
                <thead className="bg-slate-50 font-bold text-slate-700">
                  <tr>
                    <th className="px-4 py-3">Milestone</th>
                    <th className="px-4 py-3">Clause</th>
                    <th className="px-4 py-3">Timeframe</th>
                    <th className="px-4 py-3">Responsible</th>
                    <th className="px-4 py-3">Action Required</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100 bg-white">
                  {dossier.obligationCalendar.map((item, idx) => (
                    <tr key={idx} className="hover:bg-slate-50/50">
                      <td className="px-4 py-3 font-semibold text-slate-900">{item.milestone}</td>
                      <td className="px-4 py-3 text-slate-600">{item.clauseType}</td>
                      <td className="px-4 py-3 font-mono text-teal-800 font-bold">{item.timeframe}</td>
                      <td className="px-4 py-3 text-slate-600">{item.responsibleParty}</td>
                      <td className="px-4 py-3 text-slate-700">{item.actionRequired}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </article>
      ) : (
        <div className="bg-white rounded-2xl border border-slate-200 p-12 text-center space-y-3">
          <FileBadge className="w-12 h-12 text-slate-300 mx-auto" />
          <h3 className="font-bold text-sm text-slate-800">No Consultation Dossier Generated Yet</h3>
          <p className="text-xs text-slate-500 max-w-md mx-auto">
            Click "Generate Intake Brief" above to create a structured 1-page attorney preparation dossier with actionable questions and deadlines.
          </p>
        </div>
      )}
    </div>
  );
};
